const router = require("express").Router()
const postController = require("../controllers/post.controller")
router.get("/", postController.home)
router.get("/add", postController.add)
router.get("/addPost", postController.addPost)
router.post("/addPost", postController.addPostLogic)
router.get("/single/:id",postController.single)
router.get("/edit/:id",postController.edit)
router.post("/edit/:id", postController.editPost)
router.get("/delete/:id",postController.delete)
module.exports = router